DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS board;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  created TIMESTAMP NOT NULL,
  email_verified INTEGER
);


CREATE TABLE board (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created TIMESTAMP NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);


CREATE TABLE card (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  due_date TIMESTAMP,
  created TIMESTAMP NOT NULL,
  milestone TEXT, 
  label TEXT,
  status INTEGER NOT NULL,
  board_id INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (board_id) REFERENCES board (id)
);
